version: '3'

services:

  app:
    build:
      context: node
    container_name: app
    volumes:
      - ./node:/usr/src/app
    networks:
      - node-network
    ports:
      - 3000:3000
    tty: true
    depends_on:
      - db

  db: 
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    networks:
      - node-network
    tty: true

networks:
  node-network:
    driver: bridge